# Generated by Django 3.1.5 on 2021-01-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='User')),
                ('useremail', models.EmailField(max_length=128, verbose_name='Email')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='가입일시')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
